### ISSUE TITLE
Refactor non-cmssw-specific bits out of lobster.cmssw.JobProvider up to the parent class

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#85] opened 2015-03-30 20:57 UTC
We currently have four job provider configurations: 

1. lobster.job.SimpleJobProvider
2. lobster.job.JobProvider
3. lobster.cmssw.JobProvider for cmsRun jobs
4. lobster.cmssw.JobProvider for non-cmsRun jobs.

While a little confusing, the categorization makes sense: lobster.cmssw.JobProvider is not for cmsRun jobs specifically; it is for jobs for which we need the cmssw environment setup before executing. As things have evolved, a lot of stuff that is not specific to type 3 jobs above has ended up there-- most importantly, the bits having to do with file transfer in and out (currently we only have chirp and xrootd capabilities for type 3 jobs.) We should consider refactoring these bits up to the parent class.

**Comment by klannon** [comment] 2015-03-30 21:18
@annawoodard: Thanks for writing an issue for this.  I've currently assigned it to @khurtado, not because I doubt your or Matthias' ability to handle this, but because I believe that both you and Matthias have other fish to fry.  @khurtado: If its not clear what needs to be done here, then lets talk (maybe after the Thursday meeting?

**Comment by khurtado** [comment] 2015-03-30 22:13
@klannon sounds good! I understand what the issue is and what needs to be done, but I'm sure I will have questions once I start looking and working on those bits...

**Comment by matz-e** [comment] 2015-03-31 11:34
@annawoodard after our discussion yesterday, I think that maybe we should remove the the `SimpleJobProvider` and count on everything using the database?

Then the `JobHandler` could be split into one that deals with simple configurations, and a `FrameworkJobHandler`.  The wrapper would have to be "abstracted" in a similar fashion.  Then we should change the database to not have columns of run, lumi but some more generic "id" that expands to a python tuple of sorts.

Currently, I'd have some interest in getting "pythia"-style MC generation going, since I can't run this with crab ATM, which could drive this in a way…

Maybe we should have a short sync on the strategy with this?

**Comment by klannon** [comment] 2015-04-23 14:25
Based on our discussion this morning, I'm trying to indicate that this issue should be addressed before we make Lobster available to non-expert/non-ND users.  I marked the milestone as "Version 1 final" which may be hijacking the original intention of that milestone.  If you think we should have a different milestone to indicate this, that's fine too (although I'm not sure how to make new milestones...)

**Comment by matz-e** [comment] 2015-04-23 14:33
OK.  I've changed the due date of said milestone, too.

**Comment by matz-e** [comment] 2015-05-29 08:54
W.r.t. the comment of mine about a `FrameworkJobHandler`: in the `job.py` executed on the worker, we could produce a "pseudo-report" to be processed by the regular job handler.  By default, we could just assume that all files were read in, and treat a successful job to have processed everything.

Then we could allow the user to provide their own job report, and parse that, or produce the default?  Just throwing around ideas…

**Comment by annawoodard** [comment] 2015-05-29 11:12
> W.r.t. the comment of mine about a `FrameworkJobHandler`: in the `job.py` executed on the worker, we could produce a "pseudo-report" to be processed by the regular job handler.  By default, we could just assume that all files were read in, and treat a successful job to have processed everything.

+1! I vote this. This is how we do it for scriptExes in CRAB3, and it works really well.

**Comment by matz-e** [comment] 2016-01-06 10:03
I think this has been mostly resolved with the changes in the master over the last two months. Anything else would warrant it's own issue.

**Closed by matz-e** 2016-01-06 10:03 UTC
Labels: high-priority
