### ISSUE TITLE
Implement bandwidth throttling.

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#127] opened 2015-06-02 13:10 UTC
I have no idea how we can implement bandwidth throttling, but we should brainstorm and see if we can come up with something. This would be useful both for doing physics and for lobster testing to be sure that we don't get kicked off the network.

**Comment by annawoodard** [comment] 2015-06-02 13:38
It seems there are two possible approaches here: try to monitor the total PRTG traffic, or try to track the volume of input file sizes per-job. The former approach would have the benefit of working when multiple people are running at scale. The latter approach would be more generic and possibly simpler, but has a complication in that there are often auxiliary files we don't know about which add to the input bandwidth.

**Comment by klannon** [comment] 2015-06-02 14:58
I would avoid implementing something that would only work at ND (e.g. tying it to the specfic PRTG monitoring page).

**Comment by khurtado** [comment] 2015-06-02 16:37
Is this for e.g limiting lobster workers to a maximum bandwidth?

If so, I think we should use this:
https://github.com/cooperative-computing-lab/cctools/blob/3e0600a0f9f9d2dcb6cb80e841b0d6d046b31682/doc/man/work_queue_worker.m4#L53

https://github.com/cooperative-computing-lab/cctools/blob/097f0048bcc0dbb5600fff64f50108f787dd52f5/work_queue/src/work_queue.h#L475-485

**Comment by klannon** [comment] 2015-06-02 17:17
Doesn't this just limit the bandwidth of files transferred to and from the worker by WorkQueue?  If so, I don't think that addresses this question, since I believe that the bandwidth issue is really driven by XRootD access.

This will be a hard problem to tackle.  @annawoodard raises some excellent points.  I'm not sure that Lobster or even WQ by itself can handle this.  We put in a proposal a while back to try to make virtual clusters, where the workflow tools could talk to the cluster software and vice versa.  I think in that environment, you could imagine setting up a virtual cluster (or set of virtual clusters) for Lobster to run on, and tweaking the bandwidth limits on each one to keep things in the safe zone.

In the meantime, I suggest we use the simple tools that are at our disposal:  Lobster+WQ allows us to control bandwidth by deciding how many workers to run.  We just need to make sure we take care to estimate the bandwidth being used by our workers, and reduce the number of workers if we go too high.  (E.g., do this the old fashioned way.)

@annawoodard: Can we address the immediate concern by making sure the example only has the user start some really small number of workers (say 10?).  My suggestions earlier today about jobits per job are totally off-base, so ignore those (as you probably already had...).

**Comment by khurtado** [comment] 2015-06-02 17:46
In case of XRootD, there is an experimental throttle plugin that might be interesting to try:   https://twiki.cern.ch/twiki/bin/view/Main/XrootdThrottlingExperimental

Also, would tc be useful here? (just thinking loud here)

**Comment by klannon** [comment] 2015-06-02 17:47
I thought the XRootD throttle was for the server serving the data, and not the client.  Is that wrong?

I don't know what "tc" is.  Can you elaborate?

**Comment by khurtado** [comment] 2015-06-02 21:18
@klannon I think you are right ,for some reason I thought it also allowed bw limits for the user-side too.

tc (http://lartc.org/manpages/tc.txt) allows traffic shaping for outgoing and (in a trickier way that I think works for TCP packets only) incoming traffic for different rules (devices, ports, etc). But I just checked and it requires root permissions, so not a good option.

I tried iprelay, which is user-space (via sockets), but my certificates complained.
tried http://manpages.ubuntu.com/manpages/oneiric/man1/iprelay.1.html

**Comment by klannon** [comment] 2015-06-02 21:20
@khurtado: I think that @btovar and the cctools folks are working on an extension to the cctools resource monitor to include network traffic as well.  If that's true, it could be the foundation for this sort of thing.

**Comment by btovar** [comment] 2015-06-03 11:42
An update for monitoring network traffic. I have not found a solution that monitors network traffic per process that does not involve root permissions. Getting the information of the whole interface is easy, though.

**Comment by matz-e** [comment] 2015-06-03 11:43
Apart from finding the right interface, how do you divvy the bandwidth up if you're running on, e.g., cms-connect or FNAL and ND concurrently?  With a generic scope for lobster, this seems somewhat out of reach.

**Comment by btovar** [comment] 2015-06-03 12:00
Check tools like nethog. nethog examines each package and it classifies them by interface, process, etc. The problem is that you need sudo access for that.

**Comment by khurtado** [comment] 2015-06-03 15:04
@btovar So, In case of Lobster, I guess if our workflow included e.g docker images for each job all these tools would be applicable...

**Comment by btovar** [comment] 2015-06-03 15:07
That's a good point!

**Comment by klannon** [comment] 2015-06-03 15:11
Good to keep in mind, but that moves this well beyond "version 1" or perhaps even "version 2."  Correct me if I'm wrong, but docker support isn't something we can expect on an arbitrary resource, right?  That's why we use Parrot, I thought.

**Comment by khurtado** [comment] 2015-06-03 18:12
In principle, HTCondor is having a "docker universe": http://research.cs.wisc.edu/htcondor/HTCondorWeek2015/presentations//TannenbaumT_WhatsNew_May2015_v3.pdf

**Comment by klannon** [comment] 2015-06-03 18:23
Which is a good thing, but presumably, to run jobs in the Docker universe, your resources have to have Docker installed.  I'm assuming that Docker isn't something you can run from user space.  It has to be installed and run as root, right?  Please let me know if I'm confused about that.

I guess what I'm trying to say is that this is a good idea, and might even be *the* way to get this done, but if that's so, then it sets the time scale for doing this to be whenever Docker becomes a standard feature on all resources (e.g. when it's part of the standard RHX, where X >= 7?)

**Comment by khurtado** [comment] 2015-06-03 19:01
@klannon Duh! Yes, I see your point.

**Comment by matz-e** [comment] 2016-01-15 09:41
I think we have shifted this discussion to #275, thus closing this (as a sort-of duplicate).

**Closed by matz-e** 2016-01-15 09:41 UTC
