### ISSUE TITLE
Credentials expire after the user logs out of Earth

### ISSUE THREAD

**Issue by WenzhaoLi** [matz-e/lobster#616] opened 2017-11-15 09:47 UTC
When running EFT cross section jobs on Lobster, if the user logs out of Earth, the master loses the access to scratch area.

**Comment by klannon** [comment] 2017-11-15 10:01
By scratch area, do you mean the area where Lobster writes `lobster.db` and its log files?  What is the location you're putting your "scratch area."  Can you give me the path?

**Comment by WenzhaoLi** [comment] 2017-11-15 10:12
Yes, here's where I put the log files: /tmpscratch/users/wli12/ttV/cross_sections/1/

**Comment by klannon** [comment] 2017-11-15 10:16
If you're losing access to the working area in `/tmpscratch`, then something is very different than it was the last time any of us ran.  I've always put the scratch area there and 99.9% of the time Lobster is running, I've logged out.

How do you know that the problem is "credentials expiring"?

**Comment by WenzhaoLi** [comment] 2017-11-15 10:24
So Andrew ran it a few weeks ago and had this issue. He and Matthias debugged it and found that it was caused by some credentials problem. (Also because the EFT config has some special workflow)
I reproduced this error yesterday. And we are still digging into it.

**Comment by klannon** [comment] 2017-11-15 10:27
I won’t be able to help you unless you can supply more details than “some credentials problem.”  If you’ve reproduced the crash, you should at least put the relevant error message into this issue so we have somewhere to start.  Can you do that?

**Comment by WenzhaoLi** [comment] 2017-11-15 10:37
In the `process.log`, we found these
2017-11-14 15:05:25 [INFO] lobster.source: creating task(s) 36227, 36228, 36229, 36230, 36231, 36232, 36233, 36234, 36235, 36236, 36237
2017-11-14 15:05:26 [INFO] lobster.core: 0 out of 74 workers busy; 0 tasks running, 11 waiting; 4713 units left
2017-11-14 15:05:48 [ERROR] lobster.cmssw.taskhandler: error processing 36227:
[Errno 2] No such file or directory: '/tmpscratch/users/wli12/ttV/cross_sections/1/zoom_pass_1_cG/running/0003/6227/report.json'
2017-11-14 15:05:48 [ERROR] lobster.cmssw.taskhandler: error processing 36229:
[Errno 2] No such file or directory: '/tmpscratch/users/wli12/ttV/cross_sections/1/zoom_pass_1_c2W/running/0003/6229/report.json'
2017-11-14 15:05:48 [ERROR] lobster.cmssw.taskhandler: error processing 36231:
[Errno 2] No such file or directory: '/tmpscratch/users/wli12/ttV/cross_sections/1/zoom_pass_1_c6/running/0003/6231/report.json'
2017-11-14 15:05:48 [ERROR] lobster.cmssw.taskhandler: error processing 36237:
[Errno 2] No such file or directory: '/tmpscratch/users/wli12/ttV/cross_sections/1/zoom_pass_1_cl/running/0003/6237/report.json'
2017-11-14 15:05:48 [ERROR] lobster.cmssw.taskhandler: error processing 36236:
[Errno 2] No such file or directory: '/tmpscratch/users/wli12/ttV/cross_sections/1/zoom_pass_1_cl/running/0003/6236/report.json'
2017-11-14 15:05:48 [ERROR] lobster.cmssw.taskhandler: error processing 36228:
[Errno 2] No such file or directory: '/tmpscratch/users/wli12/ttV/cross_sections/1/zoom_pass_1_c3G/running/0003/6228/report.json'
2017-11-14 15:05:48 [ERROR] lobster.cmssw.taskhandler: error processing 36234:
[Errno 2] No such file or directory: '/tmpscratch/users/wli12/ttV/cross_sections/1/zoom_pass_1_cl/running/0003/6234/report.json'
2017-11-14 15:05:48 [ERROR] lobster.cmssw.taskhandler: error processing 36233:
[Errno 2] No such file or directory: '/tmpscratch/users/wli12/ttV/cross_sections/1/zoom_pass_1_c6/running/0003/6233/report.json'
2017-11-14 15:05:48 [ERROR] lobster.cmssw.taskhandler: error processing 36235:
[Errno 2] No such file or directory: '/tmpscratch/users/wli12/ttV/cross_sections/1/zoom_pass_1_cl/running/0003/6235/report.json'
2017-11-14 15:05:48 [ERROR] lobster.cmssw.taskhandler: error processing 36230:
[Errno 2] No such file or directory: '/tmpscratch/users/wli12/ttV/cross_sections/1/zoom_pass_1_c2W/running/0003/6230/report.json'
2017-11-14 15:05:48 [ERROR] lobster.cmssw.taskhandler: error processing 36232:
[Errno 2] No such file or directory: '/tmpscratch/users/wli12/ttV/cross_sections/1/zoom_pass_1_c6/running/0003/6232/report.json'
2017-11-14 15:05:49 [INFO] lobster.source: received the following task(s):
failed due to missing output: 36227, 36229, 36231, 36237, 36236, 36228, 36234, 36233, 36235, 36230, 36232
parameters and logs in:
        /tmpscratch/users/wli12/ttV/cross_sections/1/zoom_pass_1_cG/failed/0003/6227
        /tmpscratch/users/wli12/ttV/cross_sections/1/zoom_pass_1_c2W/failed/0003/6229
        /tmpscratch/users/wli12/ttV/cross_sections/1/zoom_pass_1_c6/failed/0003/6231
        /tmpscratch/users/wli12/ttV/cross_sections/1/zoom_pass_1_cl/failed/0003/6237
        /tmpscratch/users/wli12/ttV/cross_sections/1/zoom_pass_1_cl/failed/0003/6236
        /tmpscratch/users/wli12/ttV/cross_sections/1/zoom_pass_1_c3G/failed/0003/6228
        /tmpscratch/users/wli12/ttV/cross_sections/1/zoom_pass_1_cl/failed/0003/6234
        /tmpscratch/users/wli12/ttV/cross_sections/1/zoom_pass_1_c6/failed/0003/6233
        /tmpscratch/users/wli12/ttV/cross_sections/1/zoom_pass_1_cl/failed/0003/6235
        /tmpscratch/users/wli12/ttV/cross_sections/1/zoom_pass_1_c2W/failed/0003/6230
        /tmpscratch/users/wli12/ttV/cross_sections/1/zoom_pass_1_c6/failed/0003/6232

**Comment by klannon** [comment] 2017-11-15 10:46
So, fraom this output, the only thing you can conclude is that the files couldn't be opened.  This might be because of an authorization/access problem, or it could be because those files don't exist.  How can you be sure the files actually existed but the problem was in accessing them?  I can't see any of the missing files/directories, so presumably Lobster cleans them up after the crash.

**Comment by WenzhaoLi** [comment] 2017-11-15 10:55
Yes. We are still digging to find more info.. The conclusion was drawn a few weeks ago.. 
I just want to log the issue here so that we won't forget it.. (My description of the issue might not be precise)

**Comment by klannon** [comment] 2017-11-15 12:46
Understood.  But if you want help, you need to provide as much information as you can in the issue.  I think it would be good if @annawoodard looks at this to give us some ideas of what could be going wrong.

**Comment by annawoodard** [comment] 2017-11-15 15:50
Hi @WenzhaoLi! Looking at the first log file listed in the snipped you pasted `/tmpscratch/users/wli12/ttV/cross_sections/1/zoom_pass_1_cG/failed/0003/6227/task.log.gz`, I see this:

```
 === creating new release CMSSW_7_4_7 for scram arch  @ Tue Nov 14 15:05:33 EST 2017
ERROR: Unable to find release area for "CMSSW" version "CMSSW_7_4_7" for arch slc7_amd64_gcc493.
```
It looks like you are running on an slc7 machine? What command did you use to start the factory? Note that the [instructions](https://github.com/annawoodard/EffectiveTTVProduction/blob/master/README.md) recommend:

```
nohup work_queue_factory -T condor -M lobster_$USER.*ttV.*cross_sections.* -d all -o /tmp/${USER}_lobster_ttV_factory.debug -C $(readlink -f factory_cross_sections_CRC.json) --wrapper "python /afs/crc.nd.edu/group/ccl/software/runos/runos.py rhel6" --extra-options="--workdir=/disk" --worker-binary=/afs/crc.nd.edu/group/ccl/software/x86_64/redhat6/cctools/$cctools/bin/work_queue_worker >&  /tmp/${USER}_lobster_ttV.log &
```

**Comment by WenzhaoLi** [comment] 2017-11-15 16:29
Hi @annawoodard , thanks for the debugging! 
I used ```nohup work_queue_factory -T condor -M "lobster_$USER.*" -dall -o /tmp/${USER}_factory.debug -C examples/factory.json > /tmp/${USER}_factory.log &``` . 
I was running on slc7 without Singularity... Let me try submitting one more job with Singularity...

**Comment by annawoodard** [comment] 2017-11-15 16:33
I see that you only have an slc6 sandbox: `/tmpscratch/users/wli12/ttV/cross_sections/1/sandbox-CMSSW_7_4_7-slc6_amd64_gcc491-3d508e4.tar.bz2`. To run without singularity, you'd need an slc7 sandbox. You can do so if you compile cmssw on an slc7 machine and then add it to your lobster config. I haven't done any testing on slc7 though.

**Comment by annawoodard** [comment] 2017-11-15 16:34
Note also that the example factory configuration is just a starting point; in general it needs to be tweaked to the actual resource needs of your jobs. That's why a dedicated factory is included in the ttV repo.

**Comment by klannon** [comment] 2017-11-15 16:37
My suggestion: Use Singularity, don’t try to build CMSSW for slc7.

**Comment by WenzhaoLi** [comment] 2017-11-15 16:47
Thanks for the suggestion. I just started a new run with Singularity.

**Comment by annawoodard** [comment] 2017-11-15 20:54
Running with Singularity fixed the problem, so I'm closing the issue.

**Closed by annawoodard** 2017-11-15 20:54 UTC
